import type { Localized } from "../i18n";
const en = {
  help: "Controls & how it works",
  invite: "Let it loose on this page",
  commands: "Commands",
  backstage: "Behind this site",
  search: "Search commands…",
  empty: "No matching commands.",
  close: "Close",
  blueprint: "Toggle blueprint",
  blueprintOff: "Exit blueprint",
  snake: "Snake: devour the page",
  extra: "Another experiment:",
  intro: "A few decisions behind the experience you’re browsing.",
  cards: [
    [
      "Content first",
      "Complete HTML is generated at build time in three languages. React adds interaction after the page loads.",
    ],
    [
      "Small, deliberate motion",
      "The portrait blinks occasionally. Reduced motion preferences are respected, and animations pause when the tab is hidden.",
    ],
    [
      "Keyboard included",
      "Native dialogs, restored focus, semantic sections and browser accessibility tests are part of the implementation.",
    ],
  ],
  hint: "Explore the layout with blueprint, or discover a small game hidden in the page.",
  copied: "Email copied",
  failed: "Could not copy the email.",
  gameTitle: "Snake between the lines",
  gameHelp:
    "Devour the page. Click, tap, or use arrows / WASD to guide. Space pauses. Esc brings everything back.",
  score: "Score",
  pause: "Pause",
  resume: "Resume",
  restart: "Restart",
  over: "You met your tail. Try again?",
  won: "Every letter collected!",
  unavailable:
    "This browser cannot run the letter effect. You can still play the original Snake.",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
};
export const featureCopy: Localized<typeof en> = {
  en,
  pt: {
    help: "Controles e como jogar",
    invite: "Soltar a cobra nesta página",
    commands: "Comandos",
    backstage: "Por trás deste site",
    search: "Buscar comandos…",
    empty: "Nenhum comando encontrado.",
    close: "Fechar",
    blueprint: "Alternar blueprint",
    blueprintOff: "Sair do blueprint",
    snake: "Snake: devorar a página",
    extra: "Outro experimento:",
    intro: "Algumas decisões por trás da experiência que você está navegando.",
    cards: [
      [
        "Conteúdo primeiro",
        "O HTML completo é gerado no build em três idiomas. O React adiciona interação depois que a página carrega.",
      ],
      [
        "Movimento na medida",
        "O retrato pisca de vez em quando. A preferência por movimento reduzido é respeitada, e as animações pausam quando a aba fica oculta.",
      ],
      [
        "Teclado incluído",
        "Diálogos nativos, restauração de foco, seções semânticas e testes de acessibilidade no navegador fazem parte da implementação.",
      ],
    ],
    hint: "Explore a estrutura com o blueprint ou descubra um pequeno jogo escondido na página.",
    copied: "E-mail copiado",
    failed: "Não foi possível copiar o e-mail.",
    gameTitle: "Snake entre as linhas",
    gameHelp:
      "Devore a página. Clique, toque ou use setas / WASD para guiar. Espaço pausa. Esc traz tudo de volta.",
    score: "Score",
    pause: "Pausar",
    resume: "Continuar",
    restart: "Recomeçar",
    over: "Você encontrou a própria cauda. Tentar de novo?",
    won: "Todas as letras coletadas!",
    unavailable:
      "Este navegador não suporta o efeito nas letras. Você ainda pode jogar o Snake original.",
    up: "Cima",
    down: "Baixo",
    left: "Esquerda",
    right: "Direita",
  },
  es: {
    help: "Controles y cómo jugar",
    invite: "Soltar la serpiente en esta página",
    commands: "Comandos",
    backstage: "Detrás de este sitio",
    search: "Buscar comandos…",
    empty: "No hay comandos coincidentes.",
    close: "Cerrar",
    blueprint: "Alternar blueprint",
    blueprintOff: "Salir del blueprint",
    snake: "Snake: devorar la página",
    extra: "Otro experimento:",
    intro: "Algunas decisiones detrás de la experiencia que estás explorando.",
    cards: [
      [
        "El contenido primero",
        "El HTML completo se genera durante el build en tres idiomas. React añade interacción después de cargar la página.",
      ],
      [
        "Movimiento justo",
        "El retrato parpadea de vez en cuando. Se respeta el movimiento reducido y las animaciones se pausan cuando la pestaña está oculta.",
      ],
      [
        "Teclado incluido",
        "Diálogos nativos, restauración del foco, secciones semánticas y pruebas de accesibilidad en el navegador forman parte de la implementación.",
      ],
    ],
    hint: "Explora la estructura con blueprint o descubre un pequeño juego escondido en la página.",
    copied: "Correo copiado",
    failed: "No se pudo copiar el correo.",
    gameTitle: "Snake entre líneas",
    gameHelp:
      "Devora la página. Haz clic, toca o usa flechas / WASD para guiar. Espacio pausa. Esc restaura todo.",
    score: "Score",
    pause: "Pausar",
    resume: "Continuar",
    restart: "Reiniciar",
    over: "Te encontraste con tu cola. ¿Otra vez?",
    won: "¡Todas las letras recogidas!",
    unavailable:
      "Este navegador no admite el efecto en las letras. Puedes jugar al Snake original.",
    up: "Arriba",
    down: "Abajo",
    left: "Izquierda",
    right: "Derecha",
  },
};
