export const toolSites = {
  "React Native": "https://reactnative.dev/",
  Expo: "https://expo.dev/",
  Kotlin: "https://kotlinlang.org/",
  "React Navigation": "https://reactnavigation.org/",
  Reanimated: "https://docs.swmansion.com/react-native-reanimated/",
  NativeWind: "https://www.nativewind.dev/",
  React: "https://react.dev/",
  "Next.js": "https://nextjs.org/",
  Vue: "https://vuejs.org/",
  TypeScript: "https://www.typescriptlang.org/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  HTML: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  CSS: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "Tailwind CSS": "https://tailwindcss.com/",
  "Three.js": "https://threejs.org/",
  Storybook: "https://storybook.js.org/",
  "TanStack Query": "https://tanstack.com/query/latest",
  Zustand: "https://zustand.docs.pmnd.rs/",
  Redux: "https://redux.js.org/",
  MobX: "https://mobx.js.org/",
  GraphQL: "https://graphql.org/",
  Zod: "https://zod.dev/",
  "React Hook Form": "https://react-hook-form.com/",
  "Node.js": "https://nodejs.org/",
  NestJS: "https://nestjs.com/",
  Express: "https://expressjs.com/",
  "REST APIs": "https://developer.mozilla.org/en-US/docs/Glossary/REST",
  MongoDB: "https://www.mongodb.com/",
  SQLite: "https://sqlite.org/",
  Supabase: "https://supabase.com/",
  PostgreSQL: "https://www.postgresql.org/",
  Drizzle: "https://orm.drizzle.team/",
  Firebase: "https://firebase.google.com/",
  Railway: "https://railway.com/",
  Infisical: "https://infisical.com/",
  Git: "https://git-scm.com/",
  "GitHub Actions": "https://github.com/features/actions",
  GitLab: "https://about.gitlab.com/",
  "Azure DevOps": "https://azure.microsoft.com/en-us/products/devops/",
  AWS: "https://aws.amazon.com/",
  "Amazon S3": "https://aws.amazon.com/s3/",
  Azure: "https://azure.microsoft.com/",
  Clerk: "https://clerk.com/",
  OpenAI: "https://openai.com/",
  "AI SDK": "https://ai-sdk.dev/",
  Mastra: "https://mastra.ai/",
  Inngest: "https://www.inngest.com/",
  "Trigger.dev": "https://trigger.dev/",
  Jest: "https://jestjs.io/",
  Cypress: "https://www.cypress.io/",
  Maestro: "https://maestro.dev/",
  Playwright: "https://playwright.dev/",
  Sentry: "https://sentry.io/",
  Rollbar: "https://rollbar.com/",
  Statsig: "https://www.statsig.com/",
  PostHog: "https://posthog.com/",
  LaunchDarkly: "https://launchdarkly.com/",
  Figma: "https://www.figma.com/",
  "Google Maps": "https://mapsplatform.google.com/",
  Stream: "https://getstream.io/",
  Typesense: "https://typesense.org/",
  Algolia: "https://www.algolia.com/",
  "Customer.io": "https://customer.io/",
  Intercom: "https://www.intercom.com/",
  Java: "https://dev.java/",
  "C#": "https://dotnet.microsoft.com/en-us/languages/csharp",
  "Ruby on Rails": "https://rubyonrails.org/",
  C: "https://www.open-std.org/jtc1/sc22/wg14/",
  "C++": "https://isocpp.org/",
} as const;
export type ToolName = keyof typeof toolSites;
